title: "Carenza Williams"
title_separator: "|"
subtitle: "PhD Candidate"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: sunrise
markdown: kramdown
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Author Sidebar
author:
  name: "Carenza Williams"
  avatar: "assets/images/profile.png"
  bio: "Arctic Physical Oceanographer"
  location: "Johns Hopkins University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cmfwilliams/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/carenza-williams-940063224/"

# Reading Files
include:
  - .htaccess
  - _pages

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
